DROP TABLE IF EXISTS custaframe_purchase_orders;

CREATE TABLE custaframe_purchase_order(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    customers_file TEXT,
    date TIMESTAMPTZ DEFAULT now() NOT NULL,
    frame_name TEXT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    note TEXT,
    total_price INTEGER
)