DROP TABLE IF EXISTS custaframe_purchase_orders;

CREATE TABLE custaframe_purchase_order(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    customers_file URL,
    frame_name TEXT NOT NULL,
    width NUMBER NOT NULL,
    height NUMBER NOT NULL,
    note TEXT 
)